project_id = "uirbicdwikvgnuounlia"

[functions.generate-insights]
verify_jwt = true

[functions.external-api]
enabled = true
verify_jwt = true
import_map = "./functions/external-api/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/external-api/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/external-api/*.html" ]

[functions.hello-vyr]
enabled = true
verify_jwt = true
import_map = "./functions/hello-vyr/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-vyr/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-vyr/*.html" ]
